blank_issues_enabled: true

# contact_links:
#   - name: Documentation
#     url: https://github.com/lpoaura/lpo_qgis_profiles
#     about: Please read carefully the documentation before to submit an issue.
